name: reborn
description: A library to build a simple http server.
version: 0.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  meta: ^1.9.1
  mime_type: ^1.0.0
  mime: ^1.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
